title: "Niquapod's Quest for Knowledge"
author:
  name: niquapod
  email: niquapod@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  My plan for this site is to use it to track my progress through the rooms of TryHackMe and keep notes about the tools and commands used so I don't always have to go digging for a notebook and search through hardcopy for notes when I try to use them again later.
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: dark

  # generate social links in footer
  social_links:
    # - { platform: devto,          user_url: "https://dev.to/jekyll" }
    # - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
    # - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
    # - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
    - { platform: github,         user_url: "https://github.com/niquapod" }
    # - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
    # - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
    # - { platform: keybase,        user_url: "https://keybase.io/niquapod" }
    # - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
    # - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
    # - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
    # - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
    # - { platform: telegram,       user_url: "https://t.me/jekyll" }
    - { platform: twitter,        user_url: "https://twitter.com/niquapod" }
    # - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }
    - { platform: mastodon,         user_url: "https://infosec.exchange/@niquapod" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima
# remote_theme: pages-themes/hacker@v0.2.0

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme

#jekyll-archives:
 # enabled: all
  # layouts:
    # year: year-archive
    # month: month-archive
    # tag: tag-archive
  # permalinks:
    # year: '/archives/year/:year/'
    # month: '/archives/month/:year-:month/'
    # day: '/:year/:month/:day/'
    # tag: '/archives/tag/:name/'

  slug_mode: latin

# Archives
collections:
  archives: 
    output: true
    permalink: /archives/:path/
